services:
  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: jenkins-main
    user: root
    ports:
      - "9060:8080"
      - "50000:50000"
    environment:
      - JAVA_OPS=-Xmx1g
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/jenkins:/var/jenkins_home
    restart: always

  spring-boot:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-boot
    restart: unless-stopped
    ports:
      - 8076:8076
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms512m -Xmx1024m
    depends_on:
      - mysql

  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-app
    restart: unless-stopped
    ports:
      - 8077:8077

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'E103_DB'
    ports:
      - 3307:3306
    volumes:
      - my-sql-volume:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  my-sql-volume: