services:
  spring-boot:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-boot
    restart: unless-stopped
    ports:
      - 8076:8076
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms512m -Xmx1024m
    depends_on:
      - mysql

  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-app
    restart: unless-stopped
    ports:
      - 8077:8077

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "E103_DB"
    ports:
      - 3307:3306
    volumes:
      - my-sql-volume:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  openvidu:
    image: docker.io/openvidu/openvidu-server:3.0.0
    platform: linux/amd64
    restart: unless-stopped
    container_name: openvidu
    ports:
      - 3478:3478/udp
      - 7881:7881/tcp
      - 7900-7999:7900-7999/udp
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
      - ./scripts/entrypoint_openvidu.sh:/scripts/entrypoint.sh

volumes:
  my-sql-volume:
