redis:
    address: redis:6379
    username: ""
    db: 0
    use_tls: false
api_key: APIvUVrV9J2oem4
api_secret: bfKEA7T8sqG4pPEfWF89txe1UdGcaT2kxC0dvin18lLA
ws_url: ws://openvidu:7880
rtmp_port: 1935
whip_port: 8085
http_relay_port: 9090
health_port: 9091
logging:
    json: false
    level: ""
development: false
rtc_config:
    udp_port: 7895
