services:  
  nodeapp:
    build:
      context: .
      dockerfile: ./app/Dockerfile.dev
    ports:
      - "6080:6080"
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - livekit
      - redis
    env_file:
      - ./app/.env

    
  redis:
    image: docker.io/redis:7.4.1-alpine
    platform: linux/amd64
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    command: >
      redis-server
      --bind 0.0.0.0
    networks:
      - redis-network
volumes:
  redis:

networks:
  redis-network:
    driver: bridge
    external: true

